# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a75a3a51afc3e96c6842205f73f27b83b141ac3153de346849e2c4e515732ff8449d9dc3f0d2280a6bd91ef9cc2b619525c3d16ff9d4f45c31a31d6058f03d98

test:
  secret_key_base: d68f2d5764f9ae8f118329892275ee604d044c5fefe91ec91d72644d362e91eb4ca88e4c4997f9933dbae737ab84317ddc79b713eabbdbf7661f856c2ed2764e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
